spring:
  datasource:
    url: "jdbc:mariadb://localhost:3306/team_mosk_dev"
    username: "admin"
    password: "ghdtjdals7"
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        
filePath: /home/ec2-user/mosk-img
basicFilePath: classpath:img/basic.jpg
