server:
  port: 9090

jwt:
  header: Authorization
  secret: d8028ea5f26cdd3c639ffadd5f29675090f7630e6cfbd40991cd57bd78c5212ecbc0a2d1feddecc8e424fa32d31afe926b49b98c5e17dfd1760297449fc0b8ca
  accessToken-validity-in-seconds: 3600 # 1??
  refreshToken-validity-in-seconds: 18000 # 5??

apiKey:
  toss: test_sk_O6BYq7GWPVvvpLEpBxlVNE5vbo1d
  gongGongData: y3VIhvpKbdXiPhDgY5dMR8eIRvYV3Tg2zy7ySnet4Ow4rI+T/wXYfuZ3o5r9OwL9355ZQhBNTVmC54Ng+6PsEg==

storePageUrl: "http://localhost:3030/"
qrImgWidthHeight: "500x500"

spring:
  h2:
    console:
      enabled: true

#  datasource:
#    url: jdbc:h2:mem:~/testdb

---
spring:
  config:
    activate:
      on-profile: mac

  datasource:
    url: "jdbc:mariadb://localhost:3306/mosk"
    username: root
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        default_batch_fetch_size: 100

filePath: /Users/hhpp1205/Documents/mosk-img/
basicFilePath: classpath:img/basic.jpg
---
spring:
  config:
    activate:
      on-profile: windows

filePath: C:\Users\bae\Desktop\study\mosk-img\
basicFilePath: classpath:img/basic.jpg
---
spring:
  config:
    activate:
      on-profile: test

filePath: img/
basicFilePath: classpath:img/basic.jpg

