spring:
  datasource:
    url: "jdbc:mariadb://localhost:3306/team-mosk-dev"
    username: "team-mosk-dev"
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        show_sql: true